server:
  port: 8082

spring:
  application:
    name: capstone

  # Database
  # Docker 환경에서는 'localhost' 대신 'mysql' 서비스 이름 사용 (docker-compose에서 설정)
  datasource:
    url: ${MYSQL_URL}
    # 환경 변수에서 값 주입
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA
  jpa:
    hibernate:
      ddl-auto: update #none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # MySQL 8.0 버전에 맞는 Dialect 사용 권장
        dialect: org.hibernate.dialect.MySQL8Dialect

  # File Upload
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB      # 최대 파일 크기
      max-request-size: 10MB   # 최대 요청 크기

# File Upload Directory
file:
  upload-dir: uploads/board-images

# JWT
jwt:
  # 환경 변수에서 값 주입
  secret: ${JWT_SECRET_KEY}
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000